# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- nano
pool:
  name: 'my-agent-pool'
stages:
  - stage: stage1
    jobs:
      - job: job1
        steps:
          - script: echo 1
  - stage: stage2
    jobs:
        - job: job2
          steps:
            - script: echo 2
